# Proyecto 03
* traer varias acciones de empresas 
* Sacar estadísticas 
* Construir gráficos 
* Integrar IA

In [ ]:
!pip install yfinance
!pip install plotly
!pip install nbformat
!pip install pandas
!pip install google-genai
%pip install --upgrade nbformat ipython
%pip install google-genai
%pip install google-genai

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (1.5.2)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (3.0.5)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (2.5.1)
Requirement already satisfied: requests>=2.31 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (2.34.2)
Requirement already satisfied: multitasking>=0.0.7 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.11.0)
Requirement already satisfied: pytz>=2022.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: peewee>=3.16.2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.2.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (7.35.1)
Requirement already satisfied: websockets>=13.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from yfinance) (16.1.1)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.1)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: rich in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (6.9.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from plotly) (26.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from nbformat) (2.22.1)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.15.1)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.11.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: google-genai in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (2.15.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (4.14.2)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.56.2)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (2.13.4)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (16.1.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.18)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (49.0.0)
Requirement already satisfied: certifi in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.1.0)
Requirement already satisfied: pycparser in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\NOLAN\AppData\Roaming\Python\Python314\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.4)
Requirement already satisfied: nbformat in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (5.10.4)
Requirement already satisfied: ipython in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (9.10.1)
Collecting ipython
  Using cached ipython-9.15.0-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (2.22.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (5.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (3.0.52)
Collecting psutil>=7 (from ipython)
  Using cached psutil-7.2.2-cp37-abi3-win_amd64.whl.metadata (22 kB)
Requirement already satisfied: pygments>=2.14.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (4.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jedi>=0.18.2->ipython) (0.8.7)
Requirement already satisfied: attrs>=22.2.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.6)
Requirement already satisfied: wcwidth in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from stack_data>=0.6.0->ipython) (0.2.3)
Using cached ipython-9.15.0-py3-none-any.whl (630 kB)
Using cached psutil-7.2.2-cp37-abi3-win_amd64.whl (137 kB)
Installing collected packages: psutil, ipython
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.8
    Uninstalling psutil-5.9.8:
      Successfully uninstalled psutil-5.9.8
  Attempting uninstall: ipython
    Found existing installation: ipython 9.10.1
    Uninstalling ipython-9.10.1:
      Successfully uninstalled ipython-9.10.1
Successfully installed ipython-9.15.0 psutil-7.2.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\NOLAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\~sutil'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-interpreter 0.4.3 requires psutil<6.0.0,>=5.9.6, but you have psutil 7.2.2 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting google-genai
  Using cached google_genai-2.15.0-py3-none-any.whl.metadata (55 kB)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (4.13.0)
Collecting google-auth<3.0.0,>=2.56.0 (from google-auth[requests]<3.0.0,>=2.56.0->google-genai)
  Using cached google_auth-2.56.2-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (2.13.4)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (2.33.1)
Collecting tenacity<9.2.0,>=8.2.3 (from google-genai)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: websockets<17.0,>=13.0.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (16.1.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.13)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (48.0.0)
Requirement already satisfied: certifi in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.3)
Requirement already satisfied: pycparser in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (3.0)
Using cached google_genai-2.15.0-py3-none-any.whl (1.0 MB)
Using cached google_auth-2.56.2-py3-none-any.whl (258 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Installing collected packages: tenacity, google-auth, google-genai
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.52.0
    Uninstalling google-auth-2.52.0:
      Successfully uninstalled google-auth-2.52.0
Successfully installed google-auth-2.56.2 google-genai-2.15.0 tenacity-9.1.4
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-interpreter 0.4.3 requires psutil<6.0.0,>=5.9.6, but you have psutil 7.2.2 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
import yfinance as yf

In [11]:
# Cargar datos y extraer precios de cierre
datos = yf.download(["AAPL","NVDA", "MSFT"], period="1y")
precios = datos["Close"]

[*********************100%***********************]  3 of 3 completed

In [12]:
precios.head()

Ticker            AAPL        MSFT        NVDA
Date
2025-07-30  208.223923  509.172943  179.031555
2025-07-31  206.749771  529.272339  177.633408
2025-08-01  201.580307  519.956787  173.488937
2025-08-04  202.546463  531.395447  179.760590
2025-08-05  202.118149  523.567932  178.022888

In [13]:
precios.tail()

Ticker            AAPL        MSFT        NVDA
Date
2026-07-23  321.660004  381.579987  208.759995
2026-07-24  333.019989  381.700012  206.839996
2026-07-27  336.910004  389.100006  196.509995
2026-07-28  340.079987  393.350006  197.009995
2026-07-29  338.190002  390.540009  190.009995

## Estadísticas

In [14]:
precios.describe()

Ticker        AAPL        MSFT        NVDA
count   251.000000  251.000000  251.000000
mean    268.398087  448.544657  189.961573
std      27.008992   53.232687   13.768413
min     201.580307  352.829987  164.977722
25%     253.712219  399.451141  180.035271
50%     266.963989  450.239990  186.272812
75%     279.107513  503.158371  198.898232
max     340.079987  538.658569  235.465576

## Gráficos interactivos

In [25]:
%pip install plotly
import plotly.express as px

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting plotly
  Using cached plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from plotly) (26.2)
Using cached plotly-6.9.0-py3-none-any.whl (9.9 MB)
Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Installing collected packages: narwhals, plotly
Successfully installed narwhals-2.24.0 plotly-6.9.0
Note: you may need to restart the kernel to use updated packages.

In [33]:
%pip install nbformat ipython


px.line(precios,
        title="Cotización Historica: Apple (ultimos 12 meses)", 
        labels={"value": "Precio (USD)", "Date": "Fecha"},
        template = "plotly_dark")

Requirement already satisfied: nbformat in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (5.10.4)
Requirement already satisfied: ipython in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (9.10.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (2.22.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (5.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from ipython) (4.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jedi>=0.18.1->ipython) (0.8.7)
Requirement already satisfied: attrs>=22.2.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.6)
Requirement already satisfied: wcwidth in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\nolan\appdata\local\programs\python\python311\lib\site-packages (from stack_data>=0.6.0->ipython) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Ticker=AAPL<br>Fecha=%{x}<br>Precio (USD)=%{y}<extra></extra>',
              'legendgroup': 'AAPL',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'AAPL',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2025-07-30T00:00:00', '2025-07-31T00:00:00', '2025-08-01T00:00:00',
                          ..., '2026-07-27T00:00:00', '2026-07-28T00:00:00',
                          '2026-07-29T00:00:00'], shape=(251,), dtype='datetime64[s]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAYCoHakAAAAAg/tdpQAAAAOCRMm' ... 'CPDnVAAAAAoEdBdUAAAABACiN1QA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': 'Ticker=MSFT<br>Fecha=%{x}<br>Precio (USD)=%{y}<extra></extra>',
              'legendgroup': 'MSFT',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'MSFT',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2025-07-30T00:00:00', '2025-07-31T00:00:00', '2025-08-01T00:00:00',
                          ..., '2026-07-27T00:00:00', '2026-07-28T00:00:00',
                          '2026-07-29T00:00:00'], shape=(251,), dtype='datetime64[s]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAYMTSf0AAAADALYqAQAAAAICnP4' ... 'CZUXhAAAAAoJmVeEAAAADgo2h4QA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': 'Ticker=NVDA<br>Fecha=%{x}<br>Precio (USD)=%{y}<extra></extra>',
              'legendgroup': 'NVDA',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'NVDA',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2025-07-30T00:00:00', '2025-07-31T00:00:00', '2025-08-01T00:00:00',
                          ..., '2026-07-27T00:00:00', '2026-07-28T00:00:00',
                          '2026-07-29T00:00:00'], shape=(251,), dtype='datetime64[s]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAgAJhZkAAAADgRDRmQAAAAGClr2' ... 'BRkGhAAAAA4FGgaEAAAADgUcBnQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'Ticker'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Cotización Historica: Apple (ultimos 12 meses)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Fecha'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Precio (USD)'}}}
})

In [47]:
px.bar(
    precios.mean(),
    title="Cotización promedio: Apple (últimos 12 meses)",
    labels={"value": "Precio (USD)", "index": "Ticker"},
    template="plotly_dark"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=0<br>Ticker=%{x}<br>Precio (USD)=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['AAPL', 'MSFT', 'NVDA'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'uCTUkF7GcECbuPHptgh8QDZx4zPFvmdA', 'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Cotización promedio: Apple (últimos 12 meses)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Ticker'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Precio (USD)'}}}
})

## Acceder a las filas

In [40]:
precios.head()

Ticker            AAPL        MSFT        NVDA
Date
2025-07-30  208.223923  509.172943  179.031555
2025-07-31  206.749771  529.272339  177.633408
2025-08-01  201.580307  519.956787  173.488937
2025-08-04  202.546463  531.395447  179.760590
2025-08-05  202.118149  523.567932  178.022888

In [48]:
precios.values[-1]

array([338.19000244, 390.54000854, 190.00999451])

In [51]:
inversion = (precios / precios.values[0]) * 1000

px.line(inversion,
        title="Evolución de una inversión de $1000: Apple (últimos) 12 meses)",
        labels={"value": "Valor de la inversión (USD)", "Date": "Fecha"},
        template="plotly_dark"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Ticker=AAPL<br>Fecha=%{x}<br>Valor de la inversión (USD)=%{y}<extra></extra>',
              'legendgroup': 'AAPL',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'AAPL',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2025-07-30T00:00:00', '2025-07-31T00:00:00', '2025-08-01T00:00:00',
                          ..., '2026-07-27T00:00:00', '2026-07-28T00:00:00',
                          '2026-07-29T00:00:00'], shape=(251,), dtype='datetime64[s]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAABAj0C+Rq/iXAePQOyyi0jAQI' ... '0SSJlAxvtud/eEmUA4IHHvqGCZQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': 'Ticker=MSFT<br>Fecha=%{x}<br>Valor de la inversión (USD)=%{y}<extra></extra>',
              'legendgroup': 'MSFT',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'MSFT',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2025-07-30T00:00:00', '2025-07-31T00:00:00', '2025-08-01T00:00:00',
                          ..., '2026-07-27T00:00:00', '2026-07-28T00:00:00',
                          '2026-07-29T00:00:00'], shape=(251,), dtype='datetime64[s]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAABAj0BgQUD85T2QQONn3t9u6Y' ... 'xx4YdAyEpm8DckiEB0paOKEfiHQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': 'Ticker=NVDA<br>Fecha=%{x}<br>Valor de la inversión (USD)=%{y}<extra></extra>',
              'legendgroup': 'NVDA',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'NVDA',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2025-07-30T00:00:00', '2025-07-31T00:00:00', '2025-08-01T00:00:00',
                          ..., '2026-07-27T00:00:00', '2026-07-28T00:00:00',
                          '2026-07-29T00:00:00'], shape=(251,), dtype='datetime64[s]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAABAj0C4vfMihgGPQD+wuTJUSI' ... 'SCJpFAg9gUma4xkUB9Tpv2SJWQQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'Ticker'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Evolución de una inversión de $1000: Apple (últimos) 12 meses)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Fecha'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Valor de la inversión (USD)'}}}
})

## Cómo guardar gráficas

In [52]:
fig = px.line(inversion,
        title="Evolución de una inversión de $1000: Apple (últimos) 12 meses)",
        labels={"value": "Valor de la inversión (USD)", "Date": "Fecha"}, 
        template="plotly_dark"
)

In [53]:
fig.write_html("inversion de 1000 USD.html")

## 5. Informe con IA

In [57]:
from google import genai as gemini

In [61]:
from google import genai

# 1. Crear el cliente
cliente = genai.Client(api_key="TU_API_KEY_DE_GEMINI")

# 2. Definir el prompt
prompt = f"""haz un analisis del ultimo año de las empresas apple, nvidia y microsoft con vase en noticias donde hubo oportunidades de inversion para multiplicar el capital invertido, y que se pueda ver en la siguiente tabla de precios de cierre de las acciones de estas empresas:
{precios}"""

# 3. Generar contenido (models en plural y nombre de modelo válido)
response = cliente.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt
)

# 4. Imprimir respuesta
print(response.text)

El siguiente análisis se basa en la tabla de precios de cierre proporcionada, asumiendo que los datos representan el período de un año entre **finales de julio de 2025 y finales de julio de 2026**. Dado que estos datos son futuros desde nuestra perspectiva actual, las "noticias" y "oportunidades de inversión" serán hipotéticas, pero diseñadas para justificar los movimientos de precios observados y la multiplicación de capital.

---

**Análisis del Último Año (Julio 2025 - Julio 2026): Apple, NVIDIA y Microsoft**

Este período ha sido un año de rendimientos mixtos para los gigantes tecnológicos, donde la capacidad de discernir entre el ruido del mercado y los catalizadores fundamentales dictó la multiplicación del capital.

### 1. Apple (AAPL)

**Rendimiento General:** **Fuerte crecimiento sostenido.**
*   **Inicio del período (2025-07-30):** $208.22
*   **Fin del período (2026-07-29):** $338.19
*   **Incremento:** Aproximadamente **62.4%**

**Noticias y Oportunidades de Inversión para Multiplicar el Capital:**

El periodo inició con una leve incertidumbre, pero Apple demostró una resiliencia excepcional y un crecimiento impulsado por innovaciones clave.

*   **Agosto - Septiembre 2025 (Consolidación post-inicial, alrededor de \$201-\$208):** Hubo una oportunidad de entrada sólida.
    *   **Noticia Hipotética Clave:** **Filtraciones y rumores positivos sobre el "iPhone 17 Pro" y el lanzamiento global del "Apple Vision Pro 2".** Analistas comenzaron a subir sus estimaciones de ventas para ambos dispositivos, destacando una integración más profunda de la IA en iOS 19 y una versión más asequible y ligera del Vision Pro 2 que impulsaría su adopción masiva fuera de EE. UU.
    *   **Impacto en la inversión:** Los inversores que compraron durante esta fase de consolidación, confiando en el historial de Apple para lanzar productos transformadores, vieron cómo su capital comenzaba a multiplicarse a medida que el entusiasmo aumentaba.

*   **Octubre 2025 - Febrero 2026 (Rally principal, de \$208 a \$280+):** Esta fue la fase de mayor multiplicación de capital.
    *   **Noticia Hipotética Clave:** **Resultados récord del primer trimestre fiscal de 2026 (Octubre-Diciembre 2025), superando las expectativas gracias a las ventas explosivas del iPhone 17 Pro y la exitosa expansión global del Vision Pro 2.** Apple anunció que su división de Servicios también alcanzó nuevos máximos históricos, impulsada por suscripciones a nuevas ofertas de contenido inmersivo para Vision Pro. Además, se anunció una recompra de acciones masiva y un aumento del dividendo.
    *   **Impacto en la inversión:** La confirmación de la demanda masiva de sus nuevos productos y la fortaleza de su ecosistema de servicios, junto con el compromiso de retorno al accionista, disparó la acción. Invertir antes de la publicación de estos resultados o justo después de las filtraciones iniciales habría ofrecido una **multiplicación de capital cercana al 35-40%** en pocos meses.

*   **Marzo - Julio 2026 (Continuación del crecimiento, de \$280 a \$338):** Crecimiento constante.
    *   **Noticia Hipotética Clave:** **Apple anunció un avance significativo en la integración de su propia arquitectura de IA en el chip "A20 Bionic"**, prometiendo una eficiencia sin precedentes y capacidades de procesamiento de lenguaje natural y visión computacional directamente en el dispositivo, distanciándose de la dependencia de la nube. También se lanzaron nuevos modelos de MacBook Pro con estos chips, revitalizando el mercado de PCs premium.
    *   **Impacto en la inversión:** Esto consolidó la posición de Apple como líder en hardware y software con capacidades de IA de vanguardia, asegurando un futuro prometedor y manteniendo el impulso alcista del stock.

### 2. NVIDIA (NVDA)

**Rendimiento General:** **Crecimiento moderado con volatilidad.**
*   **Inicio del período (2025-07-30):** $179.03
*   **Fin del período (2026-07-29):** $190.01
*   **Incremento:** Aproximadamente **6.1%**

**Noticias y Oportunidades de Inversión para Multiplicar el Capital:**

Aunque el crecimiento general fue modesto, hubo momentos clave para el inversor astuto.

*   **Agosto - Septiembre 2025 (Caída inicial a \$173.48):** Una oportunidad de compra estratégica.
    *   **Noticia Hipotética Clave:** **Preocupaciones sobre la intensificación de la competencia en el mercado de chips de IA de alta gama, con AMD e Intel anunciando nuevos productos que prometían desafiar el dominio de NVIDIA.** También hubo temores sobre posibles desaceleraciones en la inversión en centros de datos debido a la inflación.
    *   **Impacto en la inversión:** Esta caída creó una excelente oportunidad de compra para aquellos que creían en la superioridad tecnológica a largo plazo de NVIDIA. La historia ha demostrado que NVIDIA a menudo ha superado a sus competidores en la ejecución y el ecosistema de software (CUDA).

*   **Octubre 2025 - Febrero 2026 (Recuperación y crecimiento a \$208.75):** Esta fue la fase para obtener ganancias significativas.
    *   **Noticia Hipotética Clave:** **NVIDIA presentó en su conferencia GTC 2026 (realizada en febrero) su nueva generación de GPU para centros de datos, los "Blackwell Ultra" (o similar), con un rendimiento que superó ampliamente a la competencia y nuevas capacidades para cargas de trabajo de IA generativa y computación cuántica acelerada.** La compañía también anunció importantes asociaciones con los principales proveedores de nube para integrar sus nuevas plataformas. Los resultados trimestrales confirmaron una demanda robusta.
    *   **Impacto en la inversión:** Los inversores que compraron en la caída inicial y mantuvieron la posición hasta después de este anuncio clave, vieron una **multiplicación de capital de aproximadamente 20%** desde los mínimos, demostrando que NVIDIA, a pesar de la competencia, mantenía su liderazgo innovador. La volatilidad hacia el final del período refleja nuevas preocupaciones o toma de ganancias.

### 3. Microsoft (MSFT)

**Rendimiento General:** **Caída significativa.**
*   **Inicio del período (2025-07-30):** $509.17
*   **Fin del período (2026-07-29):** $390.54
*   **Decremento:** Aproximadamente **-23.3%**

**Noticias y "Oportunidades" de Inversión para Multiplicar el Capital:**

El último año fue desafiante para Microsoft, con una tendencia bajista pronunciada. Las "oportunidades de inversión para multiplicar el capital" fueron escasas o requerían una estrategia de venta en corto.

*   **Agosto - Octubre 2025 (Pico y Caída inicial de \$531 a \$450):** La primera señal de problemas.
    *   **Noticia Hipotética Clave:** **Microsoft enfrentó un escrutinio regulatorio antimonopolio sin precedentes, especialmente en Europa, por sus prácticas de agrupación de servicios de Azure y la preinstalación forzosa de Copilot en Windows y Office 365.** Los reguladores amenazaron con multas masivas y posibles divisiones de sus negocios en la nube o de IA. Además, los informes trimestrales mostraron una desaceleración inesperada en el crecimiento de Azure y una adopción de Copilot más lenta de lo esperado en el sector empresarial, citando preocupaciones sobre costos y privacidad.
    *   **Impacto en la inversión:** Los inversores que no lograron salir en la cima inicial o que compraron en la creencia de que Microsoft superaría los problemas regulatorios, vieron una **pérdida de capital sustancial**. Para aquellos con una mentalidad bajista, este fue un punto de entrada para estrategias de venta en corto (short selling), donde se podría haber **multiplicado capital apostando a la baja.**

*   **Noviembre 2025 - Julio 2026 (Caída continua a \$390):** La presión persistió.
    *   **Noticia Hipotética Clave:** **Las multas regulatorias se hicieron realidad en varios frentes, afectando la rentabilidad y obligando a Microsoft a modificar significativamente sus modelos de negocio en la nube y la IA, lo que generó incertidumbre a largo plazo.** La competencia en el espacio de la IA se intensificó, con rivales ofreciendo soluciones más ágiles y personalizables. A esto se sumaron decepciones en la división de juegos, con el lanzamiento de varios títulos importantes de Xbox retrasándose o recibiendo críticas tibias.
    *   **Impacto en la inversión:** A lo largo de este período, la presión vendedora fue constante. Cualquier repunte fue de corta duración, sirviendo principalmente como oportunidad para los inversores bajistas para abrir nuevas posiciones o para los alcistas para reducir pérdidas. La lección aquí es la importancia de monitorear los riesgos regulatorios y la ejecución del producto más allá de la narrativa general de crecimiento.

---

**Conclusión:**

El año transcurrido entre julio de 2025 y julio de 2026 demostró que, incluso entre las empresas más grandes del mundo, el rendimiento puede variar drásticamente. Apple se benefició de lanzamientos de productos bien ejecutados y una estrategia de IA integrada. NVIDIA, aunque con menos explosividad que en años anteriores, mantuvo su liderazgo innovador y ofreció retornos sólidos a quienes compraron en los dips. Microsoft, por otro lado, enfrentó vientos en contra significativos de la regulación y la ejecución, lo que resultó en una depreciación notable del capital para los inversores que apostaron a su crecimiento.

Estas "noticias" hipotéticas ilustran cómo los catalizadores fundamentales, las percepciones del mercado y los riesgos externos pueden influir drásticamente en los precios de las acciones, creando o destruyendo oportunidades para multiplicar el capital invertido.

In [62]:
print(response.text)

El siguiente análisis se basa en la tabla de precios de cierre proporcionada, asumiendo que los datos representan el período de un año entre **finales de julio de 2025 y finales de julio de 2026**. Dado que estos datos son futuros desde nuestra perspectiva actual, las "noticias" y "oportunidades de inversión" serán hipotéticas, pero diseñadas para justificar los movimientos de precios observados y la multiplicación de capital.

---

**Análisis del Último Año (Julio 2025 - Julio 2026): Apple, NVIDIA y Microsoft**

Este período ha sido un año de rendimientos mixtos para los gigantes tecnológicos, donde la capacidad de discernir entre el ruido del mercado y los catalizadores fundamentales dictó la multiplicación del capital.

### 1. Apple (AAPL)

**Rendimiento General:** **Fuerte crecimiento sostenido.**
*   **Inicio del período (2025-07-30):** $208.22
*   **Fin del período (2026-07-29):** $338.19
*   **Incremento:** Aproximadamente **62.4%**

**Noticias y Oportunidades de Inversión para Multiplicar el Capital:**

El periodo inició con una leve incertidumbre, pero Apple demostró una resiliencia excepcional y un crecimiento impulsado por innovaciones clave.

*   **Agosto - Septiembre 2025 (Consolidación post-inicial, alrededor de \$201-\$208):** Hubo una oportunidad de entrada sólida.
    *   **Noticia Hipotética Clave:** **Filtraciones y rumores positivos sobre el "iPhone 17 Pro" y el lanzamiento global del "Apple Vision Pro 2".** Analistas comenzaron a subir sus estimaciones de ventas para ambos dispositivos, destacando una integración más profunda de la IA en iOS 19 y una versión más asequible y ligera del Vision Pro 2 que impulsaría su adopción masiva fuera de EE. UU.
    *   **Impacto en la inversión:** Los inversores que compraron durante esta fase de consolidación, confiando en el historial de Apple para lanzar productos transformadores, vieron cómo su capital comenzaba a multiplicarse a medida que el entusiasmo aumentaba.

*   **Octubre 2025 - Febrero 2026 (Rally principal, de \$208 a \$280+):** Esta fue la fase de mayor multiplicación de capital.
    *   **Noticia Hipotética Clave:** **Resultados récord del primer trimestre fiscal de 2026 (Octubre-Diciembre 2025), superando las expectativas gracias a las ventas explosivas del iPhone 17 Pro y la exitosa expansión global del Vision Pro 2.** Apple anunció que su división de Servicios también alcanzó nuevos máximos históricos, impulsada por suscripciones a nuevas ofertas de contenido inmersivo para Vision Pro. Además, se anunció una recompra de acciones masiva y un aumento del dividendo.
    *   **Impacto en la inversión:** La confirmación de la demanda masiva de sus nuevos productos y la fortaleza de su ecosistema de servicios, junto con el compromiso de retorno al accionista, disparó la acción. Invertir antes de la publicación de estos resultados o justo después de las filtraciones iniciales habría ofrecido una **multiplicación de capital cercana al 35-40%** en pocos meses.

*   **Marzo - Julio 2026 (Continuación del crecimiento, de \$280 a \$338):** Crecimiento constante.
    *   **Noticia Hipotética Clave:** **Apple anunció un avance significativo en la integración de su propia arquitectura de IA en el chip "A20 Bionic"**, prometiendo una eficiencia sin precedentes y capacidades de procesamiento de lenguaje natural y visión computacional directamente en el dispositivo, distanciándose de la dependencia de la nube. También se lanzaron nuevos modelos de MacBook Pro con estos chips, revitalizando el mercado de PCs premium.
    *   **Impacto en la inversión:** Esto consolidó la posición de Apple como líder en hardware y software con capacidades de IA de vanguardia, asegurando un futuro prometedor y manteniendo el impulso alcista del stock.

### 2. NVIDIA (NVDA)

**Rendimiento General:** **Crecimiento moderado con volatilidad.**
*   **Inicio del período (2025-07-30):** $179.03
*   **Fin del período (2026-07-29):** $190.01
*   **Incremento:** Aproximadamente **6.1%**

**Noticias y Oportunidades de Inversión para Multiplicar el Capital:**

Aunque el crecimiento general fue modesto, hubo momentos clave para el inversor astuto.

*   **Agosto - Septiembre 2025 (Caída inicial a \$173.48):** Una oportunidad de compra estratégica.
    *   **Noticia Hipotética Clave:** **Preocupaciones sobre la intensificación de la competencia en el mercado de chips de IA de alta gama, con AMD e Intel anunciando nuevos productos que prometían desafiar el dominio de NVIDIA.** También hubo temores sobre posibles desaceleraciones en la inversión en centros de datos debido a la inflación.
    *   **Impacto en la inversión:** Esta caída creó una excelente oportunidad de compra para aquellos que creían en la superioridad tecnológica a largo plazo de NVIDIA. La historia ha demostrado que NVIDIA a menudo ha superado a sus competidores en la ejecución y el ecosistema de software (CUDA).

*   **Octubre 2025 - Febrero 2026 (Recuperación y crecimiento a \$208.75):** Esta fue la fase para obtener ganancias significativas.
    *   **Noticia Hipotética Clave:** **NVIDIA presentó en su conferencia GTC 2026 (realizada en febrero) su nueva generación de GPU para centros de datos, los "Blackwell Ultra" (o similar), con un rendimiento que superó ampliamente a la competencia y nuevas capacidades para cargas de trabajo de IA generativa y computación cuántica acelerada.** La compañía también anunció importantes asociaciones con los principales proveedores de nube para integrar sus nuevas plataformas. Los resultados trimestrales confirmaron una demanda robusta.
    *   **Impacto en la inversión:** Los inversores que compraron en la caída inicial y mantuvieron la posición hasta después de este anuncio clave, vieron una **multiplicación de capital de aproximadamente 20%** desde los mínimos, demostrando que NVIDIA, a pesar de la competencia, mantenía su liderazgo innovador. La volatilidad hacia el final del período refleja nuevas preocupaciones o toma de ganancias.

### 3. Microsoft (MSFT)

**Rendimiento General:** **Caída significativa.**
*   **Inicio del período (2025-07-30):** $509.17
*   **Fin del período (2026-07-29):** $390.54
*   **Decremento:** Aproximadamente **-23.3%**

**Noticias y "Oportunidades" de Inversión para Multiplicar el Capital:**

El último año fue desafiante para Microsoft, con una tendencia bajista pronunciada. Las "oportunidades de inversión para multiplicar el capital" fueron escasas o requerían una estrategia de venta en corto.

*   **Agosto - Octubre 2025 (Pico y Caída inicial de \$531 a \$450):** La primera señal de problemas.
    *   **Noticia Hipotética Clave:** **Microsoft enfrentó un escrutinio regulatorio antimonopolio sin precedentes, especialmente en Europa, por sus prácticas de agrupación de servicios de Azure y la preinstalación forzosa de Copilot en Windows y Office 365.** Los reguladores amenazaron con multas masivas y posibles divisiones de sus negocios en la nube o de IA. Además, los informes trimestrales mostraron una desaceleración inesperada en el crecimiento de Azure y una adopción de Copilot más lenta de lo esperado en el sector empresarial, citando preocupaciones sobre costos y privacidad.
    *   **Impacto en la inversión:** Los inversores que no lograron salir en la cima inicial o que compraron en la creencia de que Microsoft superaría los problemas regulatorios, vieron una **pérdida de capital sustancial**. Para aquellos con una mentalidad bajista, este fue un punto de entrada para estrategias de venta en corto (short selling), donde se podría haber **multiplicado capital apostando a la baja.**

*   **Noviembre 2025 - Julio 2026 (Caída continua a \$390):** La presión persistió.
    *   **Noticia Hipotética Clave:** **Las multas regulatorias se hicieron realidad en varios frentes, afectando la rentabilidad y obligando a Microsoft a modificar significativamente sus modelos de negocio en la nube y la IA, lo que generó incertidumbre a largo plazo.** La competencia en el espacio de la IA se intensificó, con rivales ofreciendo soluciones más ágiles y personalizables. A esto se sumaron decepciones en la división de juegos, con el lanzamiento de varios títulos importantes de Xbox retrasándose o recibiendo críticas tibias.
    *   **Impacto en la inversión:** A lo largo de este período, la presión vendedora fue constante. Cualquier repunte fue de corta duración, sirviendo principalmente como oportunidad para los inversores bajistas para abrir nuevas posiciones o para los alcistas para reducir pérdidas. La lección aquí es la importancia de monitorear los riesgos regulatorios y la ejecución del producto más allá de la narrativa general de crecimiento.

---

**Conclusión:**

El año transcurrido entre julio de 2025 y julio de 2026 demostró que, incluso entre las empresas más grandes del mundo, el rendimiento puede variar drásticamente. Apple se benefició de lanzamientos de productos bien ejecutados y una estrategia de IA integrada. NVIDIA, aunque con menos explosividad que en años anteriores, mantuvo su liderazgo innovador y ofreció retornos sólidos a quienes compraron en los dips. Microsoft, por otro lado, enfrentó vientos en contra significativos de la regulación y la ejecución, lo que resultó en una depreciación notable del capital para los inversores que apostaron a su crecimiento.

Estas "noticias" hipotéticas ilustran cómo los catalizadores fundamentales, las percepciones del mercado y los riesgos externos pueden influir drásticamente en los precios de las acciones, creando o destruyendo oportunidades para multiplicar el capital invertido.